# This is a basic workflow to help you get started with Actions

name: sync

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: wget jdb file
        run: |
          rm -rf *.jdb
          wget `curl -s 'https://definitions.symantec.com/defs/sonar/index.html' | grep '.jdb' | tail -3 | awk '{print $3}' | awk -F'"' '{print $2}'`
          wget `curl -s 'https://definitions.symantec.com/defs/ips/index.html' | grep '.jdb' | tail -3 | awk '{print $3}' | awk -F'"' '{print $2}'`
          wget `curl -s 'https://definitions.symantec.com/defs/download/symantec_enterprise/jdb/core3sds/index.html' | grep '.jdb' | tail -3 | awk '{print $3}' | awk -F'"' '{print $2}'`
          
      - name: Delete release
        run: |
          gh release delete ${{ github.ref }} -y
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Upload jdb to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./*.jdb
          tag: ${{ github.ref }}
          overwrite: true

